
- name: reinstate data files
  command: cp {{ backup_root }}/{{ item }} {{ server_root }}/{{ item }}
  register: command_response
  with_items:
   - "meta.db"
   - "recentPlacements.txt"
   - "lastEveLocation.txt" 
   - "eveRadius.txt"
   - "playerStats.db"
   - "eve.db"
   - "lookTime.db"
   - "map.db"
   - "mapTime.db"
   - "biome.db"
   - "grave.db"
   - "floorTime.db"
   - "floor.db"
   - "log.txt"
   - "biomeRandSeed.txt"
   - "clientTagLog.txt"
   - "curseWordList.txt"
   - "familyDataLog.txt"
   - "femaleNames.txt"
   - "firstNames.txt"
   - "kissTest.txt"
   - "lastNames.txt"
   - "maleNames.txt"
   - "namesInfo.txt"
   - "protocol.txt"
   - "sampleTestMap.txt"
   - "serverCodeVersionNumber.txt"
   - "wordList.txt"
  failed_when: "'No such file or directory' not in command_response.stderr and '' not in command_response.stderr"

- name: reinstate settings
  command: cp {{ backup_root }}/settings/{{ item }} {{ server_root }}/settings/{{ item }}
  register: command_response
  with_items:
   - "eveMovingGridJump.ini"
   - "lifeTokenServerSharedSecret.ini"
   - "useEveMovingGrid.ini"
   - "sequenceNumber.ini"
   - "homesickEmotionIndex.ini"
   - "childSameRaceLikelihood.ini"
   - "curseTokenTime.ini"
   - "edgeObject.ini"
   - "secondsPerYear.ini"
   - "killDelayTime.ini"
   - "killEmotionIndex.ini"
   - "useTestMap.ini"
   - "clientPassword.ini"
   - "useFitnessServer.ini"
   - "killerVulnerableSeconds.ini"
   - "foodScaleFactorFloor.ini"
   - "foodScaleFactorGamma.ini"
   - "namedRedeemPhrases.ini"
   - "eatCostMax.ini"
   - "barrierRadius.ini"
   - "propUpWeakestFamily.ini"
   - "foodScaleFactorHalfLife.ini"
   - "curseBlockDuration.ini"
   - "shortLifeAge.ini"
   - "reflectorSharedSecret.ini"
   - "languageLearningRate.ini"
   - "numTilesExaminedPerCullStep.ini"
   - "allowBugReports.ini"
   - "eatBonusHalfLife.ini"
   - "namedFollowPhrases.ini"
   - "specialMapPlacements.ini"
   - "curseThreshold.ini"
   - "minActivePlayersForSpecialBiomes.ini"
   - "newPlayerMessageForMother.ini"
   - "pastPlayerFlushSeconds.ini"
   - "eveInjectionOn.ini"
   - "orderPhrase.ini"
   - "satisfiedEmotionIndex.ini"
   - "baseToolSlotsPerPlayer.ini"
   - "babySurvivalYearsBeforeApocalypse.ini"
   - "minFamiliesAfterEveWindow.ini"
   - "babyFeedingLevel.ini"
   - "barrierObjects.ini"
   - "targetPlayersPerFamily.ini"
   - "minPotentialFertileFemalesPerFamily.ini"
   - "weakFamilyPickWaitSecondsPerMom.ini"
   - "forceEveAge.ini"
   - "eveInjectionFitnessWindow.ini"
   - "offspringGivingPhrases.ini"
   - "reflectorURL.ini"
   - "backupHourUTC.ini"
   - "serverID.ini"
   - "deathStaggerTime.ini"
   - "barrierOn.ini"
   - "curseBlockOfflineExponent.ini"
   - "minActivePlayersForLongTermCulling.ini"
   - "eveToWestOfHomelands.ini"
   - "cursingPhrases.ini"
   - "namedKillPhrases.ini"
   - "forceEveObject.ini"
   - "minActivePlayersForLanguages.ini"
   - "mapRequestAllowAccounts.ini"
   - "lineageServerURL.ini"
   - "allowedEmotRange.ini"
   - "eveWindowSeconds.ini"
   - "requireClientPassword.ini"
   - "babyToPlayerApocalypseRatio.ini"
   - "babySurvivalWindowSecondsBeforeApocalypse.ini"
   - "arcServerSharedSecret.ini"
   - "canYumChainBreak.ini"
   - "youExilePhrases.ini"
   - "posseSpeedMultipliers.ini"
   - "minActivePlayersForToolSlots.ini"
   - "statsServerSharedSecret.ini"
   - "curseDistance.ini"
   - "lineageLimitOneLineHours.ini"
   - "arcServerURL.ini"
   - "blockEveRespawn.ini"
   - "curseBabyPhrase.ini"
   - "useCurseServer.ini"
   - "allowMapRequests.ini"
   - "fitnessServerURL.ini"
   - "curseDecrementTime.ini"
   - "nurseCost.ini"
   - "allowCrossLineageCursing.ini"
   - "eatBonusFloor.ini"
   - "skipUseDummyCleanup.ini"
   - "arcStartTime.ini"
   - "babyBirthFoodDecrement.ini"
   - "propUpWeakestRace.ini"
   - "longTermNoLookCullSeconds.ini"
   - "usePersonalCurses.ini"
   - "babyNamingPhrases.ini"
   - "homelandStaleSeconds.ini"
   - "forgiveYouPhrases.ini"
   - "forceShutdownMode.ini"
   - "lifeTokenServerURL.ini"
   - "skipRemovedObjectCleanup.ini"
   - "minPosseFraction.ini"
   - "minAgeForCravings.ini"
   - "mapCellForgottenSeconds.ini"
   - "minPosseCap.ini"
   - "port.ini"
   - "victimEmotionIndex.ini"
   - "maxFoodDecrementSeconds.ini"
   - "saveBackups.ini"
   - "babyBones.ini"
   - "cravingPoolExponent.ini"
   - "nextPlayerID.ini"
   - "shutdownMode.ini"
   - "statsServerURL.ini"
   - "eveMovingGridRows.ini"
   - "youGivingPhrases.ini"
   - "curseServerSharedSecret.ini"
   - "familySpan.ini"
   - "orderDistance.ini"
   - "newPlayerLifeCount.ini"
   - "clearCurseCountsOnStartup.ini"
   - "familyLimitAfterEveWindow.ini"
   - "allowVOGMode.ini"
   - "curseBlockOfflineFactor.ini"
   - "eveInjectionFamilyRatio.ini"
   - "specialBiomes.ini"
   - "forbiddenEmots.ini"
   - "maxLanguageLearningAge.ini"
   - "longTermNoLookCullEnabled.ini"
   - "curseYouPhrase.ini"
   - "minActivePlayersForEveWindow.ini"
   - "useArcServer.ini"
   - "remoteReport.ini"
   - "cravingPoolOffset.ini"
   - "minActivePlayersForBabyApocalypse.ini"
   - "forgivingPhrases.ini"
   - "minActivePlayersForFitness.ini"
   - "forceSpawnAccounts.ini"
   - "vogAllowAccounts.ini"
   - "foodScaleFactor.ini"
   - "runObjectSurveyNow.ini"
   - "posseJoiningPhrases.ini"
   - "languageLearningBaseFraction.ini"
   - "flushLookTimes.ini"
   - "posseDelayReductionFactor.ini"
   - "maxBabyAdultRatio.ini"
   - "eatBonus.ini"
   - "maxToolSlotsPerPlayer.ini"
   - "forceAllPlayersEve.ini"
   - "allowTriggerRequests.ini"
   - "starvingEmotionIndex.ini"
   - "useStatsServer.ini"
   - "barrierBlocksPlanes.ini"
   - "lineageLimitOtherLineHours.ini"
   - "maxLivingChildrenPerMother.ini"
   - "valleySpacing.ini"
   - "lineageServerSharedSecret.ini"
   - "maxTwinPartySize.ini"
   - "arcRunMaxSeconds.ini"
   - "babyMotherApocalypseRatio.ini"
   - "specialBiomeSicknesses.ini"
   - "cursesUseSenderEmail.ini"
   - "eveInjectionBabyRatio.ini"
   - "familyGivingPhrases.ini"
   - "eatCostGrowthRate.ini"
   - "forceEveLocationX.ini"
   - "languageLearningRepetitionLimit.ini"
   - "possePopulationRadius.ini"
   - "fitnessServerSharedSecret.ini"
   - "apocalypseBroadcast.ini"
   - "minFoodDecrementSeconds.ini"
   - "namedAfterKillPhrases.ini"
   - "curseBlockRadius.ini"
   - "ticketServerURL.ini"
   - "photoServerSharedSecret.ini"
   - "nextEveJump.ini"
   - "victimTerrifiedEmotionIndex.ini"
   - "forceEveLocationY.ini"
   - "maxBabyMomRatio.ini"
   - "biomeWeights.ini"
   - "noCullItemList.ini"
   - "useLifeTokenServer.ini"
   - "requireTicketServerCheck.ini"
   - "familyNamingPhrases.ini"
   - "recentScoreWindowForPickingEve.ini"
   - "yumBonusCap.ini"
   - "minEveCampRespawnAge.ini"
   - "minRebirthDistance.ini"
   - "indoorFoodDecrementSecondsBonus.ini"
   - "forceEveLocation.ini"
   - "useLineageServer.ini"
   - "curseServerURL.ini"
   - "maxEveStartupLocationUsage.ini"
   - "forceEveAfterGenerationNumber.ini"
   - "youKillPhrases.ini"
   - "youFollowPhrases.ini"
   - "raceSpecialBiomes.ini"
   - "homeEmotionIndex.ini"
   - "maxFlightDistance.ini"
   - "maxPlayers.ini"
   - "babyApocalypsePossible.ini"
   - "useCurseWords.ini"
   - "newPlayerLifeTotalSeconds.ini"
   - "babyBonesGround.ini"
   - "epochSeconds.ini"
   - "keepBackupsDays.ini"
   - "skipLookTimeCleanup.ini"
   - "namedGivingPhrases.ini"
   - "namedExilePhrases.ini"
   - "requireClientForceAck.ini"
   - "biomeOrder.ini"
   - "youRedeemPhrases.ini"
   - "eveName.ini"
   - "apocalypsePossible.ini"
   - "refuseFoodEmotionIndex.ini"
  failed_when: "'No such file or directory' not in command_response.stderr and '' not in command_response.stderr"

- name: reinstate logs
  command: cp -R {{ backup_root }}/{{ item }}/* {{ server_root }}/{{ item }}/
  register: command_response
  with_items:
   - "lifeLog"
   - "curseLog"
   - "foodLog"
   - "failureLog"
  failed_when: "'No such file or directory' not in command_response.stderr and '' not in command_response.stderr"

