- name: install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git 
    - g++ 
    - imagemagick 
    - xclip 
    - libsdl1.2-dev 
    - libglu1-mesa-dev 
    - libgl1-mesa-dev

- git:
    repo: 'https://github.com/jasonrohrer/minorGems.git'
    dest: /opt/onelife/minorGems

# force yes allow repo to be updated/clone with existance of custom configuration
- git:
    repo: 'https://github.com/jasonrohrer/OneLife.git'
    dest: /opt/onelife/OneLife
    force: yes

- git:
    repo: 'https://github.com/jasonrohrer/OneLifeData7.git'
    dest: /opt/onelife/OneLifeData7

- name: checkout most up to date versions of repositories
  shell: |
     #!/bin/bash

     cd /opt/onelife/minorGems
     git fetch --tags
     latestTaggedVersion=`git for-each-ref --sort=-creatordate --format '%(refname:short)' --count=1 refs/tags/OneLife_v* | sed -e 's/OneLife_v//'`
     git checkout -q OneLife_v$latestTaggedVersion

     cd /opt/onelife/OneLife
     git fetch --tags
     latestTaggedVersionA=`git for-each-ref --sort=-creatordate --format '%(refname:short)' --count=1 refs/tags/OneLife_v* | sed -e 's/OneLife_v//'`
     git checkout -q OneLife_v$latestTaggedVersionA

     cd /opt/onelife/OneLifeData7
     git fetch --tags
     latestTaggedVersionB=`git for-each-ref --sort=-creatordate --format '%(refname:short)' --count=1 refs/tags/OneLife_v* | sed -e 's/OneLife_v//'`
     git checkout -q OneLife_v$latestTaggedVersionB

     rm -f */cache.fcz

- file:
    src: '/opt/onelife/OneLifeData7/{{ item.src }}'
    dest: '/opt/onelife/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'animations', dest: 'animations' }
    - { src: 'categories', dest: 'categories' }
    - { src: 'ground', dest: 'ground' }
    - { src: 'music', dest: 'music' }
    - { src: 'objects', dest: 'objects' }
    - { src: 'sounds', dest: 'sounds' }
    - { src: 'sprites', dest: 'sprites' }
    - { src: 'transitions', dest: 'transitions' }
    - { src: 'dataVersionNumber.txt', dest: 'dataVersionNumber.txt' }

- name: move build script
  copy:
    src: /opt/onelife/OneLife/build/source/runToBuild
    dest: /opt/onelife

- file:
    path: /opt/onelife/runToBuild
    state: touch
    mode: "a+x"

- name: execute build script
  shell: |
     #!/bin/bash

     cd /opt/onelife
     ./runToBuild 1
- name: configure for linux
  shell: |
     #!/bin/bash

     cd /opt/onelife/OneLife/server
     ./configure 1

- name: compile
  shell: | 
     #!/bin/bash

     cd /opt/onelife/OneLife/server
     make

- file:
    src: '/opt/onelife/OneLifeData7/{{ item.src }}'
    dest: '/opt/onelife/OneLife/server/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'objects', dest: 'objects' }
    - { src: 'transitions', dest: 'transitions' }
    - { src: 'categories', dest: 'categories' }

- name: set server to correct version
  shell: |
     #!/bin/bash

     echo $(cat /opt/onelife/dataVersionNumber.txt) > /opt/onelife/OneLife/server/serverCodeVersionNumber.txt

- name: "set requireTicketServerCheck (default: false)"
  shell: |
     #!/bin/bash

     echo "{{ ticket_check }}" > /opt/onelife/OneLife/server/settings/requireTicketServerCheck.ini

- name: "set spawn point (default: fixed)"
  shell: |
     #!/bin/bash

     echo "{{ force_eve_location }}" > /opt/onelife/OneLife/server/settings/forceEveLocation.ini
     echo "{{ eve_x }}" > /opt/onelife/OneLife/server/settings/forceEveLocationX.ini
     echo "{{ eve_y }}" > /opt/onelife/OneLife/server/settings/forceEveLocationY.ini

# allows selected port through firewall
- name: "add ufw exeption for port (default: 8005)"
  ufw:
    rule: allow
    port: "{{ port_number }}"

- name: "set spawn point (default: fixed)"
  shell: |
     #!/bin/bash
     
     echo "{{ port_number }}" > /opt/onelife/OneLife/server/settings/port.ini

- name: "set maximum amount of users (default: 160)"
  shell: |
     #!/bin/bash

     echo "{{ max_users }}" > /opt/onelife/OneLife/server/settings/maxPlayers.ini

- name: "set server password"
  shell: |
     #!/bin/bash
     
     echo "{{ server_password }}" > /opt/onelife/OneLife/server/settings/clientPassword.ini
     echo "1" > /opt/onelife/OneLife/server/settings/requireClientPassword.ini

  when: server_password is defined

- name: install onelife command line utility
  copy:
    src: source/onelife
    dest: /usr/sbin/onelife
    owner: root
    group: root
    mode: 0700

- name: install onelife ansible files
  copy:
    src: ../ansible
    dest: /usr/sbin/onelife_easy_install

- name: install onelife install script
  copy:
    src: ../install
    dest: /usr/sbin/onelife_easy_install/install
    owner: root
    group: root
    mode: 0700
