
- name: clear cache files
  shell: | 
       #!/bin/bash
       
       cd /opt/onelife/OneLifeData7
       rm -rf */cache.fcz
       rm -rf */bin_*cache.fcz

- name: make backup of the server directory
  command: cp -R {{ server_root }} {{ backup_root }}

